apiVersion: v1
description: A Helm chart for Kubernetes
name: cassandra
version: 0.1.0
icon: https://upload.wikimedia.org/wikipedia/commons/5/5e/Cassandra_logo.svg
keywords:
- cassandra
- database
- nosql
home: http://cassandra.apache.org
