image:
  repository: 127.0.0.1:31500/cassandra
  tag: latest
  pullPolicy: Always

antiAffinity: "null" # or soft or hard

probeInitialDelaySeconds: 90
probePeriodSeconds: 30

## Persist data to a persitent volume
persistence:
  type: emptyDir # or hostPath or PersistentVolumeClaim

  #storageClass:
  volumeSize: 10Gi

  hostPath: ""

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
## Minimum memory for development is 4GB and 2 CPU cores
## Minimum memory for production is 8GB and 4 CPU cores
## ref: http://docs.datastax.com/en/archived/cassandra/2.0/cassandra/architecture/architecturePlanningHardware_c.html
resources:
  requests:
    memory: 4Gi
    cpu: 2
  #limits:
  #  memory: 4Gi
  #  cpu: 2

## Change cassandra configuration paramaters below:
## ref: http://docs.datastax.com/en/cassandra/3.0/cassandra/configuration/configCassandra_yaml.html
## Recommended max heap size is 1/2 of system memory
## Recommeneed heap new size is 1/4 of max heap size
## ref: http://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsTuneJVM.html
config:
  clusterName: cassandra
  clusterSize: 3
  seedSize: 2
  numTokens: 256
  dcName: DC1
  rackName: RAC1
  endpointSnitch: SimpleSnitch
  maxHeapSize: 2048M
  heapNewSize: 512M
  ports:
    cql: 9042
    thrift: 9160

prometheus:
  jmxExporter:
    enabled: false

logCollector:
  enabled: false
  image:
    repository: mirantisworkloads/filebeat
    tag: 5.2.2
    pullPolicy: Always
  # external logstash hosts
  logstashHost:
    - "" # host:port Ex: "logstash-logstash:5043"
