spark:
  master:
    replicas: 2
  worker:
    replicas: 3

prometheusExporter:
  enabled: true

zookeeper:
  deployChart: false
  externalAddress: zk-${BFD_ZOOKEEPER_RELEASE}-0.zk-${BFD_ZOOKEEPER_RELEASE}:2181,zk-${BFD_ZOOKEEPER_RELEASE}-1.zk-${BFD_ZOOKEEPER_RELEASE}:2181,zk-${BFD_ZOOKEEPER_RELEASE}-2.zk-${BFD_ZOOKEEPER_RELEASE}:2181
