{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
  annotations:
  {{- if .Values.istio.enabled }}
    kubernetes.io/ingress.class: istio
  {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      {{- range .Values.ingress.hosts }}
      - {{ . }}
      {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - backend:
              serviceName: {{ printf "tweeviz-%s" $.Release.Name  | trunc 55 | trimSuffix "-" }}
              servicePort: {{ $.Values.port }}
    {{- end -}}
{{- end -}}
