apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "rollout.fullname" . }}-apply
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "rollout.fullname" . }}
data:
  apply: |
{{ toYaml .Values.helmApplyConfig | indent 4 }}
