apiVersion: v1
kind: Secret
metadata:
  name: {{ template "clair.fullname" . }}
  labels:
    app: {{ template "clair.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  config.yaml:
    {{- $config := include "clair.config" . }}
    {{ $config | b64enc }}
