{{- if .Values.prometheusExporter.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "cassandra.fullname" . }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "cassandra.fullname" . }}
data:
  cassandra-jmx.yml: |-
    ---
    lowercaseOutputLabelNames: true
    lowercaseOutputName: true
    rules:
    - pattern: org.apache.cassandra.metrics<type=(Connection|Streaming), scope=(\S*), name=(\S*)><>(Count|Value)
      name: cassandra_$1_$3
      labels:
        address: "$2"
    - pattern: org.apache.cassandra.metrics<type=(\S*)(?:, ((?!scope)\S*)=(\S*))?(?:, scope=(\S*))?,
        name=(\S*)><>(Count|Value)
      name: cassandra_$1_$5
      labels:
        "$1": "$4"
        "$2": "$3"
{{- end }}
