apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ printf "cm-zk-%s" .Release.Name | trunc 63 }}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: "{{ printf "zk-%s" .Release.Name  | trunc 63 }}"
data:
  zoo.cfg: |-
    tickTime={{.Values.tickTime}}
    initLimit={{.Values.initLimit}}
    syncLimit={{.Values.syncLimit}}
    autopurge.purgeInterval={{.Values.autopurge.purgeInterval}}
    autopurge.snapRetainCount={{.Values.autopurge.snapRetainCount}}
    maxClientCnxns={{.Values.maxClientCnxns}}
    dataDir=/var/lib/zookeeper/data
    dataLogDir=/var/lib/zookeeper/log
    standaloneEnabled=false
    dynamicConfigFile=/var/lib/zookeeper/conf/zoo.cfg.dynamic
    4lw.commands.whitelist=*
    reconfigEnabled=true
    skipACL=yes
