apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ printf "cm-zk-%s" .Release.Name | trunc 63 }}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: "{{ printf "zk-%s" .Release.Name  | trunc 63 }}"
data:
  zoo.cfg: |-
    tickTime={{.Values.tickTime}}
    initLimit={{.Values.initLimit}}
    syncLimit={{.Values.syncLimit}}
    autopurge.purgeInterval={{.Values.autopurge.purgeInterval}}
    autopurge.snapRetainCount={{.Values.autopurge.snapRetainCount}}
    maxClientCnxns={{.Values.maxClientCnxns}}
    dataDir=/var/lib/zookeeper/data
    dataLogDir=/var/lib/zookeeper/log
    standaloneEnabled=false
    dynamicConfigFile=/var/lib/zookeeper/conf/zoo.cfg.dynamic
    4lw.commands.whitelist=*
    reconfigEnabled=true
    skipACL=yes
  java.env: |-
    JVMFLAGS="-Xmx{{.Values.heapSize}} -Xms{{.Values.heapSize}}"
    ZOO_LOG_DIR="/var/log/zookeeper"
  log4j.properties: |-
    zookeeper.root.logger=CONSOLE
    zookeeper.console.threshold={{.Values.logLevel}}
    zookeeper.log.maxfilesize=256MB
    zookeeper.log.maxbackupindex=20
    zookeeper.log.dir=/var/log/zookeeper
    zookeeper.log.file=zookeeper.log
    log4j.rootLogger=${zookeeper.root.logger}
    log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
    log4j.appender.CONSOLE.Threshold=${zookeeper.console.threshold}
    log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
    log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} [myid:%X{myid}] - %-5p [%t:%C{1}@%L] - %m%n
