apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "rollout.fullname" . }}-rollback
  labels:
    app: {{ template "rollout.fullname" . }}-rollback
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "2"
spec:
  template:
    metadata:
      labels:
        app: {{ template "rollout.fullname" . }}-rollback
    spec:
      restartPolicy: OnFailure
      containers:
      - name: app
        image: "{{ .Values.spinnaker.jenkins.Agent.image.repository }}{{ .Values.spinnaker.jenkins.Agent.image.name }}:{{ .Values.spinnaker.jenkins.Agent.image.tag }}"
        command:
        - "sh"
        - "-cxe"
        - |
          ROLLOUT_PIPELINE_ID=$(curl -s {{ template "rollout.gate-address" . }}/pipelineConfigs |  jq -r '.[] | select(.name == "Twitter Analytics UI: Rollout").id')
          sed "s/\${ROLLOUT_PIPELINE_ID}/${ROLLOUT_PIPELINE_ID}/g" /tmp/body/rollback.json | curl -d@- -f -m 10 -H "Content-Type: application/json" -H "Accept: application/json" http://{{ template "rollout.gate-address" . }}/pipelines
        volumeMounts:
        - mountPath: /tmp/body
          name: pipeline
      volumes:
      - name: pipeline
        configMap:
          name: {{ template "rollout.fullname" . }}-rollback