apiVersion: v1
kind: Service
metadata:
  name: {{ template "ls-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "ls-fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ template "ls-fullname" . }}
  ports:
    - port: {{ .Values.port }}
      name: logstash
