apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "router-name" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "router-name" . }}
spec:
  replicas: {{ .Values.router.replicas }}
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ template "router-name" . }}
    spec:
      containers:
      - name: mongo-router
        image: {{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
          - name: MONGO_CONFIGDB_ADDRESS
            value: {{ template "cfg-address" . }}
        command:
          - dumb-init
          - "--"
          - python
          - /bootstrap.py
          - {{ .Values.router.port | quote }}
          - "router"
        readinessProbe:
          tcpSocket:
            port: {{ .Values.router.port }}
          periodSeconds: {{ .Values.router.probeTimeoutSeconds }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          - name: config
            mountPath: /etc/mongo
          {{- if .Values.logCollector.enabled }}
          - name: logdir
            mountPath: /var/log/mongodb
          {{- end }}
      {{- if .Values.logCollector.enabled }}
      - name: filebeat
        image: {{ .Values.logCollector.image.repository }}{{ .Values.logCollector.image.name }}:{{ .Values.logCollector.image.tag }}
        imagePullPolicy: {{ .Values.logCollector.image.pullPolicy | quote }}
        volumeMounts:
          - name: filebeat-config
            mountPath: /etc/filebeat
          - name: logdir
            mountPath: /opt/bitnami/mongodb/logs
        command:
          - "filebeat"
          - "-c"
          - "/etc/filebeat/filebeat.yml"
          - "-e"
          - "-d"
          - "\"*\""
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ template "router-name" . }}
      {{- if .Values.logCollector.enabled }}
      - name: logdir
        emptyDir: {}
      - name: filebeat-config
        configMap:
          name: {{ template "mongo-name" . }}
          items:
            - key: filebeat-yml
              path: filebeat.yml
      {{- end }}
