apiVersion: v1
kind: Service
metadata:
  name: {{ template "router-name" . }}
  labels:
    app: {{ template "router-name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.router.service.type }}
  sessionAffinity: "ClientIP"
  ports:
  - name: mongo
    port: {{ .Values.router.port }}
    targetPort: {{ .Values.router.port }}
  selector:
    app: {{ template "router-name" . }}
  {{- if eq .Values.router.service.type "LoadBalancer" }}
  {{- if .Values.router.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.router.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.router.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.router.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
  {{- end -}}
