apiVersion: v1
kind: Service
metadata:
  name: {{ template "rabbitmq-management.fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "rabbitmq-management.fullname" . }}
{{- if .Values.management.service.annotations }}
  annotations:
{{ toYaml .Values.management.service.annotations | indent 4}}
{{- end }}
spec:
  ports:
  - port: 15672
    name: management
    {{- if eq .Values.management.service.type "NodePort" }}
    {{- if .Values.management.service.nodePort }}
    nodePort: {{ .Values.management.service.nodePort }}
    {{- end -}}
    {{- end }}
  selector:
    app: {{ template "rabbitmq.fullname" . }}
  type: "{{ .Values.management.service.type }}"
{{- if eq .Values.management.service.type "LoadBalancer" }}
  {{- if .Values.management.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.management.service.loadBalancerIP }}
  {{- end -}}
  {{- if .Values.management.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.management.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
{{- end -}}
