apiVersion: v1
kind: Service
metadata:
  name: {{ template "influx-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "influx-fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4}}
{{- end }}
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    app: {{ template "influx-fullname" . }}
  ports:
    {{- $fullname := include "influx-fullname" . -}}
    {{ range $name, $settings := .Values.ports }}
    - name: {{ printf "%s-%s-%d-%s" $fullname ($name | lower) (int $settings.port) (default "tcp" $settings.protocol | lower) }}
      port: {{ $settings.port }}
      protocol: {{ default "tcp" $settings.protocol | upper }}
      {{- if $settings.nodePort }}
      nodePort: {{ $settings.nodePort }}
      {{- end }}
    {{- end }}
    {{- range $name, $values := .Values.additionalDatabasesInterfacesConfigs }}
    - name: {{ printf "%s-%s-%d-%s" $fullname ($name | lower) (int $values.port) (default "tcp" $values.protocol | lower) }}
      port: {{ $values.port }}
      protocol: {{ default "tcp" $values.protocol | upper }}
      {{- if $values.nodePort }}
      nodePort: {{ $values.nodePort }}
      {{- end }}
    {{- end }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.data.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
  {{- end -}}
