spark:
  master:
    replicas: 1
  worker:
    replicas: 3

zookeeper:
  deployChart: false
  externalAddress: zk-${TS_ZOOKEEPER_RELEASE}-0.zk-${TS_ZOOKEEPER_RELEASE}:2181,zk-${TS_ZOOKEEPER_RELEASE}-1.zk-${TS_ZOOKEEPER_RELEASE}:2181,zk-${TS_ZOOKEEPER_RELEASE}-2.zk-${TS_ZOOKEEPER_RELEASE}:2181
