minHashtagCounts: 0

zookeeper:
  deployChart: false
  externalAddress: zk-${TS_ZOOKEEPER_RELEASE}-0.zk-${TS_ZOOKEEPER_RELEASE}:2181,zk-${TS_ZOOKEEPER_RELEASE}-1.zk-${TS_ZOOKEEPER_RELEASE}:2181,zk-${TS_ZOOKEEPER_RELEASE}-2.zk-${TS_ZOOKEEPER_RELEASE}:2181

kafka:
  deployChart: false
  externalAddress: kafka-${TS_KAFKA_RELEASE}-0.kafka-${TS_KAFKA_RELEASE}:9092,kafka-${TS_KAFKA_RELEASE}-1.kafka-${TS_KAFKA_RELEASE}:9092,kafka-${TS_KAFKA_RELEASE}-2.kafka-${TS_KAFKA_RELEASE}:9092
  topic: twitter-stream

spark:
  deployChart: false
  externalAddress: spark-master-${TS_SPARK_RELEASE}-0:7077,spark-master-${TS_SPARK_RELEASE}-1:7077

storage: ${TS_STORAGE}

hdfs:
  deployChart: false
  externalAddress: hdfs-namenode-${TS_HDFS_RELEASE}-0.hdfs-namenode-${TS_HDFS_RELEASE}
  path: /twitter

cassandra:
  deployChart: false
  externalAddress: cassandra-${TS_CASSANDRA_RELEASE}:9042
  keyspace: mirantis
  table: tweetics
