apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "shard-name" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "shard-name" . }}
data:
  mongo.conf:
{{ toYaml .Values.shard.config | indent 4 }}

