{{- if .Values.prometheusExporter.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "shard-exporter-name" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "shard-name" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ template "shard-name" . }}
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: mongo-shard-exporter
        image: {{ .Values.prometheusExporter.image.repository }}{{ .Values.prometheusExporter.image.name }}:{{ .Values.prometheusExporter.image.tag }}
        imagePullPolicy: {{ .Values.prometheusExporter.image.pullPolicy | quote }}
        command:
          - ./mongodb_exporter
          - -logtostderr
          - -mongodb.uri
          - mongodb://{{ template "shard-address" . }}
        ports:
          - name: metrics
            containerPort: 9001
{{- end -}}
