apiVersion: v1
kind: Service
metadata:
  name: "{{ printf "kafka-%s" .Release.Name | trunc 63 }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: "{{ printf "kafka-%s" .Release.Name  | trunc 63 }}"
spec:
  ports:
  - port: {{.Values.port}}
    name: port
  clusterIP: None
  selector:
    app: "{{ printf "kafka-%s" .Release.Name  | trunc 63 }}"
