apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluent-cm-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fluent-fullname" . }}
data:
  fluentd-conf: |
    <source>
      @type  forward
      @id    input1
      @label @mainstream
      port {{ .Values.ports.fluent.port }}
    </source>

    <source>
      @type monitor_agent
      bind 0.0.0.0
      port {{ .Values.ports.monitoring.port }}
    </source>

    <filter **>
      @type stdout
    </filter>

    <label @mainstream>
      <match docker.**>
        @type file
        @id   output_docker1
        path         /fluentd/log/docker.*.log
        symlink_path /fluentd/log/docker.log
        append       true
        time_slice_format %Y%m%d
        time_slice_wait   1m
        time_format       %Y%m%dT%H%M%S%z
      </match>
      <match **>
        @type file
        @id   output1
        path         /fluentd/log/data.*.log
        symlink_path /fluentd/log/data.log
        append       true
        time_slice_format %Y%m%d
        time_slice_wait   10m
        time_format       %Y%m%dT%H%M%S%z
      </match>
    </label>
  {{- range $name, $content := .Values.configurations }}
  {{ $name }}: |
{{ $content | indent 4 }}
  {{- end }}
