apiVersion: v1
kind: Service
metadata:
  name: {{ template "fluent-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fluent-fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4}}
{{- end }}
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    app: {{ template "fluent-fullname" . }}
  ports:
    {{- $fluent_fullname := include "fluent-fullname" . -}}
    {{- range $name, $settings := .Values.ports }}
    - name: '{{ $fluent_fullname }}-{{ $name | lower }}-{{ $settings.port}}-{{ default "tcp" $settings.protocol | lower }}'
      port: {{ $settings.port }}
      protocol: {{ default "tcp" $settings.protocol | upper }}
      {{- if $settings.nodePort }}
      nodePort: {{ $settings.nodePort }}
      {{- end }}
    {{- end}}
