name: kibana
version: 1.2.5
description: |
  Kibana is an open source analytics and visualization platform
  designed to work with Elasticsearch.
appVersion: 5.2.2
icon: https://mirantisworkloads.storage.googleapis.com/icons/kibana.png
