name: kibana
version: 1.2.4
description: |
  Kibana is an open source analytics and visualization platform
  designed to work with Elasticsearch.
appVersion: 5.2.2
icon: https://www.elastic.co/assets/bltf11265439e44d327/logo-elastic-kibana-lt.svg
