port: 5601
HTTPPort: 80

replicas: 1

# The Elasticsearch instance to use for all your queries.
elasticsearch:
  external: true
  host: "" # elasticsearch cluster svc name, e.g. elasticsearch-elasticsearch
  port: 9200

elasticsearchConfig:
  preserveHost: true
  # Time in milliseconds to wait for responses from the back end or Elasticsearch.
  requestTimeout: 30000
  # Time in milliseconds for Elasticsearch to wait for responses from shards. Set to 0 to disable.
  shardTimeout: 0
  # Time in milliseconds to wait for Elasticsearch at Kibana startup before retrying.
  startupTimeout: 5000

image:
  repository: "mirantisworkloads/"
  name: "kibana"
  tag: "5.2.2"
  pullPolicy: "IfNotPresent"

testImage:
  repository: "mirantisworkloads/"
  name: "test-base"
  tag: "1.0.0"
  pullPolicy: "IfNotPresent"

# Configure resource requests and limits.
resources:
  #requests:
  #  memory: "256Mi"
  #  cpu: "250m"
  #limits:
    #cpu: "256Mi"
    #memory: "250m"

service:
  type: "ClusterIP"
  nodePort: ""
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  annotations: {}

ingress:
  enabled: false
  hosts: []
    #   - some.domain
  tls:
    enabled: false
    secretName: ""
  annotations: {}
    #   kubernetes.io/ingress.class: nginx
