{{- if .Values.Elasticsearch.Persistence.Enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  annotations:
    volume.{{ .Values.Elasticsearch.DataStorage.ClassVersion }}.kubernetes.io/storage-class: {{ .Values.Elasticsearch.DataStorage.Class | quote }}
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: {{ .Values.Elasticsearch.DataStorage.Size | quote }}
---
{{- end }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "data-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Elasticsearch.Component.Name }}"
    type: data
spec:
  replicas: {{ default 3 .Values.Elasticsearch.Data.Replicas }}
  template:
    metadata:
      name: {{ template "data-fullname" . }}
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "{{ .Release.Name }}-{{ .Values.Elasticsearch.Component.Name }}"
        type: data
      {{- if .Values.Elasticsearch.Persistence.Enabled }}
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
              "name": "elasticsearch-init",
              "image": "busybox",
              "imagePullPolicy": "IfNotPresent",
              "command": ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"],
              "volumeMounts": [
                  {
                    "name": "elasticsearch-data",
                    "mountPath": "/usr/share/elasticsearch/data"
                  }
              ]
            }
          ]'
      {{- end }}
    spec:
      {{- if .Values.Elasticsearch.Persistence.Enabled }}
      volumes:
        - name: elasticsearch-data
          persistentVolumeClaim:
            claimName: elasticsearch-pvc
      {{- end }}
      containers:
      - name: {{ .Values.Elasticsearch.Component.Name | quote }}
        env:
        - name: SERVICE
          value: {{ template "es-fullname" . }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_MASTER
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xms{{ .Values.Elasticsearch.Data.HeapSize }} -Xmx{{ .Values.Elasticsearch.Data.HeapSize }}"
        image: "{{ .Values.Elasticsearch.Image.Name }}:{{ .Values.Elasticsearch.Image.Tag }}"
        imagePullPolicy: {{ .Values.Elasticsearch.Image.PullPolicy | quote }}
        command:
          - elasticsearch
        ports:
        - containerPort: 9300
          name: transport
        resources:
{{ toYaml .Values.Elasticsearch.Data.Resources | indent 12 }}
        {{- if .Values.Elasticsearch.Persistence.Enabled }}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-data
        {{- end }}
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash","/pre-stop-hook.sh"]

