apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: {{ template "data-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  clusterIP: None
  ports:
    - port: 9300
      targetPort: 9300
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Elasticsearch.Component.Name }}"
    type: data
