apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-agent
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
spec:
  ports:
    - port: {{ .Values.Master.slaveListenerPort }}
      targetPort: {{ .Values.Master.slaveListenerPort }}
      name: slavelistener
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Master.Component }}"
  type: ClusterIP
