apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "jenkins.master-fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: {{ template "jenkins.master-fullname" . }}-master
