twitter:
  appKey: APPKEY
  appSecret: APPSECRET
  tokenKey: TOKENKEY
  tokenSecret: TOKENSECRET

  locations: -71.4415,41.9860,-70.4747,42.9041

kafka:
  deployChart: false
  externalAddress: kafka-kafka-1-0.kafka-kafka-1:9092
  topic: twitter-stream
