minPopularity: 1
topListSize: 0

service:
  type: NodePort

storage: STORAGE

hdfs:
  deployChart: false
  path: /
  externalAddress: hdfs-namenode-HDFSRELEASE-0.hdfs-namenode-HDFSRELEASE
  externalPort: 8020

cassandra:
  deployChart: false
  externalAddress: cassandra-CASRELEASE:9042
  keyspace: mirantis
  table: tweetics
