apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "akka.fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "akka.fullname" . }}
data:
  java-opts: "{{ template "akka.java_opts" . }}"
