port: 5043

replicas: 1

# elasticsearch connection values, needed to output to ES storage
elasticsearch:
 external: true
 host: "" # elasticsearch cluster svc name
 port: 9200

# image values
image:
 repository: "mirantisworkloads/"
 name: "logstash"
 tag: "5.2.2"
 pullPolicy: "IfNotPresent"

testImage:
  repository: "mirantisworkloads/"
  name: "test-base"
  tag: "1.0.0"
  pullPolicy: "IfNotPresent"

# jvm options
heapSize: "1536m"

service:
  annotations: {}

# container required resources
resources:
 #requests:
 #  memory: "2Gi"
 #  cpu: "250m"
 #limits:
 #  memory: "4Gi"
 #  cpu: "1024m"
