component: logstash
port: 5043
protocol: TCP

replicas: 1

# elasticsearch connection values, needed to output to ES storage
elasticsearch:
 service: elasticsearch-elasticsearch # elasticsearch cluster svc name
 port: 9200

# image values
image:
 repository: "127.0.0.1:31500/logstash"
 tag: "latest"
 pullPolicy: "Always"

# jvm options
heapSize: "1536m"

# container required resources
resources:
 requests:
   memory: "2Gi"
   cpu: "250m"
 limits:
   memory: "4Gi"
   cpu: "1024m"
