# If enabled, will generate the in-cluster kubeconfig (located at
# /root/.kube/config) that might be used for the distributed installation
# https://www.spinnaker.io/setup/install/environment/#distributed
prepareKubeconfig:
  enabled: true
  # Name of the context, user and cluster that will be generated
  context: default
  user: default
  cluster: default
  # The namespace Spinnaker will be deployed into. The namespace of the
  # release will be used by default. Change if necessary.
  # NOTE: The "location" parameter under "deploymentEnvironment" will be
  # set by that option.
  namespace:

image:
  repository: gcr.io/spinnaker-marketplace/
  name: halyard
  tag: stable
  pullPolicy: IfNotPresent

service:
  # K8s service to expose deck
  ui:
    type: NodePort # or ClusterIP or LoadBalancer

    port: 9000
    nodePort: ""

    loadBalancerIP: ""
    loadBalancerSourceRanges: []

    annotations: {}
  # K8s service to expose gate
  api:
    type: NodePort # or ClusterIP or LoadBalancer

    port: 8084
    nodePort: ""

    loadBalancerIP: ""
    loadBalancerSourceRanges: []

    annotations: {}

# If enabled, Minio chart will be deployed and configured as
# a storage for Spinnaker
minio:
  deployChart: true

# Halconfig file will appear at /root/.hal/config
halconfig: |
  currentDeployment: default
  deploymentConfigurations:
  - name: default
    version: 1.6.0
    providers:
      dockerRegistry:
        enabled: true
        accounts:
        - name: dockerhub
          requiredGroupMembership: []
          providerVersion: V1
          address: https://index.docker.io
          email: fake.email@spinnaker.io
          repositories:
          - library/nginx
        primaryAccount: dockerhub
      kubernetes:
        enabled: true
        accounts:
        - name: local
          requiredGroupMembership: []
          providerVersion: V1
          dockerRegistries:
          - accountName: dockerhub
            namespaces: []
          configureImagePullSecrets: true
          namespaces: []
          omitNamespaces: []
          kubeconfigFile: /root/.kube/config
          oauthScopes: []
          oAuthScopes: []
        primaryAccount: local
    deploymentEnvironment:
      size: SMALL
      type: Distributed
      accountName: local
      updateVersions: true
    persistentStorage:
      s3:
        bucket: spin-bucket
    features:
      auth: false
      fiat: false
      chaos: false
      entityTags: false
      jobs: true
      pipelineTemplates: true
      artifacts: false
    timezone: America/Los_Angeles

files:
  - path: /root/.hal/default/service-settings/deck.yml
    content: |
      env:
        API_HOST: "http://spin-gate:8084"
  - path: /root/.hal/default/service-settings/gate.yml
    content: |
      overrideBaseUrl: "/gate"

