apiVersion: v1
kind: Service
metadata:
  name: {{ template "halyard.deck.fullname" . }}
  namespace: {{ template "halyard.spinnaker-namespace" . }}
  labels:
    app: {{ template "halyard.deck.fullname" . }}
{{- if .Values.service.ui.annotations }}
  annotations:
{{ toYaml .Values.service.ui.annotations | indent 4}}
{{- end }}
spec:
  ports:
    - port: {{ .Values.service.ui.port }}
      name: http
      {{- if eq .Values.service.ui.type "NodePort" }}
      {{- if .Values.service.ui.nodePort }}
      nodePort: {{ .Values.service.ui.nodePort }}
      {{- end -}}
      {{- end }}
  selector:
    load-balancer-spin-deck: "true"
  type: "{{ .Values.service.ui.type }}"
{{- if eq .Values.service.ui.type "LoadBalancer" }}
  {{- if .Values.service.ui.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.ui.loadBalancerIP }}
  {{- end -}}
  {{- if .Values.service.ui.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.service.ui.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
{{- end -}}
