# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Master:
  Name: spark-master
  Image: localhost:31500/spark
  ImageTag: 2.1.0
  imagePullPolicy: Always
  Replicas: 1
  Component: "spark-master"
  Cpu: "100m"
  Memory: "512Mi"
  ServicePort: 7077
  ContainerPort: 7077
  # Set Master JVM memory. Default 1g
  #DaemonMemory: 1g

WebUi:
  Name: spark-webui
  ServicePort: 8080
  ContainerPort: 8080
  serviceType: ClusterIP
  #externalIPs:
  #  - ip
  #nodePort: port

Rest:
  Name: spark-restapi
  ServicePort: 6066
  ContainerPort: 6066

Worker:
  Name: spark-worker
  Image: localhost:31500/spark
  ImageTag: 2.1.0
  imagePullPolicy: Always
  Replicas: 3
  Component: "spark-worker"
  Cpu: "100m"
  Memory: "512Mi"
  ContainerPort: 8081
  # Set Worker JVM memory. Default 1g
  #DaemonMemory: 1g
  # Set how much total memory workers have to give executors
  #ExecutorMemory: 1g

Zeppelin:
  Name: zeppelin
  Image: localhost:31500/zeppelin
  ImageTag: 0.7.1
  imagePullPolicy: Always
  Replicas: 1
  Component: "zeppelin"
  Cpu: "100m"
  ServicePort: 8080
  ContainerPort: 8080
  serviceType: ClusterIP
  #externalIPs:
  #  - ip
  # nodePort: port
monitoring: false

logCollector:
  enabled: false
  image:
    repository: 127.0.0.1:31500/filebeat
    tag: latest
    pullPolicy: Always
  hosts: ["logstash-logstash:5043"]
  spark:
    currentHost: "spark"
    logsPaths:
      - "/var/log/spark"
    logsFiles:
      - "/var/log/spark/*.log"
  zeppelin:
    currentHost: "zeppelin"
    logsPaths:
      - "/zeppelin-0.7.1-bin-all/logs"
    logsFiles:
      - "/zeppelin-0.7.1-bin-all/logs/*.log"
