# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

spark:
  image:
    repository: mirantisworkloads/spark
    tag: 2.1.0
    pullPolicy: Always
  master:
    replicas: 2  # 1 or 2
    daemonMemory: "1g"
    rpcPort: 7077
    rpcNodePort: null
    webuiPort: 8080
    webuiNodePort: null
    restPort: 6066
    restNodePort: null
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
  worker:
    replicas: 3
    daemonMemory: "1g"
    executorMemory: "1g"
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"

zeppelin:
  enabled: true
  image:
    repository: mirantisworkloads/zeppelin
    tag: 0.7.1
    pullPolicy: Always
  port: 8080
  nodePort: null
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"

ingress:
  enabled: false
  hosts: []
  tls:
    enabled: false
    secretName: ""
  annotations: {}

service:
  type: ClusterIP
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  annotations: {}

prometheus:
  jmxExporter:
    enabled: true

logCollector:
  enabled: false
  image:
    repository: mirantisworkloads/filebeat
    tag: 5.2.2
    pullPolicy: Always
  # external logstash hosts
  logstashHost:
    - "" # host:port

zookeeper:
  # if disabled, subchart will not be deployed
  deployChart: true
  # this address will be used if subchart deployment is disabled
  externalAddress: ""
