kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: {{ printf "red-%s" .Release.Name | trunc 24 }}
  labels:
    app: {{ printf "red-%s" .Release.Name | trunc 24 }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: redis-sentinel
  replicas: {{ .Values.config.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ printf "red-%s" .Release.Name | trunc 24 }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      containers:
      - name: redis
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MASTER_DATA
          value: {{ .Values.config.masterData }}
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - name: redis
          containerPort: {{ default 6379 .Values.redisPort }}
        volumeMounts:
        {{- if .Values.persistence.enabled }}
        - name: data
          mountPath: {{ .Values.config.masterData }}
        {{- end }}
        - name: redis-cfg
          mountPath: /opt/redis/conf
      - name: sentinel
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SENTINEL
          value: "true"
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        ports:
        - name: sentinel
          containerPort: {{ default 26379 .Values.sentinelPort }}
        volumeMounts:
        - name: sentinel-cfg
          mountPath: /opt/redis/conf
      volumes:
      - name: redis-cfg
        configMap:
          name: {{ printf "cm-redis-%s" .Release.Name | trunc 24 }}
      - name: sentinel-cfg
        configMap:
          name: {{ printf "cm-sentinel-%s" .Release.Name | trunc 24 }}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: {{ printf "red-%s" .Release.Name | trunc 24 }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
      {{- if .Values.persistence.storageClass }}
        volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
      {{- else }}
        volume.alpha.kubernetes.io/storage-class: default
      {{- end }}
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
{{- end }}
