apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "component-fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "component-fullname" . }}
spec:
  replicas: {{ default 1 .Values.replicas }}
  template:
    metadata:
      name: {{ template "component-fullname" . }}
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ template "component-fullname" . }}
    spec:
      containers:
        - name: {{ .Values.component }}
          env:
            - name: LS_JAVA_OPTS
              value: "-Xms{{ .Values.heapSize }} -Xmx{{ .Values.heapSize }} -Djava.net.preferIPv4Stack=true"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command:
            - "logstash"
            - "-f"
            - "/etc/logstash/logstash.conf"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - containerPort: {{ .Values.port }}
              protocol: {{ default "TCP" .Values.protocol }}
          volumeMounts:
            - name: config
              mountPath: /etc/logstash
      volumes:
        - name: config
          configMap:
            name: {{ template "component-fullname" . }}-cm
            items:
              - key: logstash-conf
                path: logstash.conf
