apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "schema-registry.fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "schema-registry.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "schema-registry.fullname" . }}
    spec:
      containers:
      - name: schema-registry
        image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: {{ template "schema-registry.zk-address" . }}
        ports:
        - name: api
          containerPort: {{ .Values.port }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      {{ if .Values.ui.enabled }}
      - name: schema-registry-ui
        image: "{{ .Values.ui.image.repository }}{{ .Values.ui.image.name }}:{{ .Values.ui.image.tag }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        env:
        - name: SCHEMAREGISTRY_URL
          value: {{ template "schema-registry.address" . }}
        - name: PROXY
          value: "true"
        ports:
        - name: ui
          containerPort: {{ .Values.ui.port }}
      {{- end -}}
