apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ printf "bfd-spark-digest-%s" .Release.Name  | trunc 55 | trimSuffix "-" }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ printf "bfd-spark-digest-%s" .Release.Name  | trunc 55 | trimSuffix "-" }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        heritage: "{{ .Release.Service }}"
        release: "{{ .Release.Name }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ printf "bfd-spark-digest-%s" .Release.Name  | trunc 55 | trimSuffix "-" }}
    spec:
      containers:
      - name: spark-digest
        image: {{ .Values.spark.spark.image.repository }}{{ .Values.spark.spark.image.name }}:{{ .Values.spark.spark.image.tag }}
        imagePullPolicy: {{ .Values.spark.spark.image.pullPolicy }}
        command:
        - bash
        - -c
        - |
          curl -o spark-digest.jar https://oss.sonatype.org/content/repositories/snapshots/de/nierbeck/floating/data/spark-digest_2.11/0.4.0-SNAPSHOT/spark-digest_2.11-0.4.0-SNAPSHOT-assembly.jar
          spark-submit {{ index .Values.digest "submit-args" }} --master spark://{{ template "bfd.spark-address" . }} --class de.nierbeck.floating.data.stream.spark.KafkaToCassandraSparkApp spark-digest.jar METRO-Vehicles {{ template "bfd.cassandra-host" . }}:{{ template "bfd.cassandra-port" . }} {{ template "bfd.kafka-address" . }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
