spark:
  master:
    replicas: 2
  worker:
    replicas: 3

service:
  type: NodePort

zookeeper:
  deployChart: false
  externalAddress: zk-zookeeper-1-0.zk-zookeeper-1:2181,zk-zookeeper-1-1.zk-zookeeper-1:2181,zk-zookeeper-1-2.zk-zookeeper-1:2181
