# Default values for mongodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: mirantisworkloads/
  name: mongodb
  tag: "3.4-r5"
  pullPolicy: Always

configServer:
  replicas: 3
  port: 27019

shard:
  replicas: 3
  port: 27019

router:
  replicas: 2
  port: 27017
  service:
    type: ClusterIP
    nodePort: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    annotations: {}

resources:
  requests:
    cpu: 100m
    memory: 128Mi

logCollector:
  enabled: false
  image:
    repository: mirantisworkloads/
    name: filebeat
    tag: 5.2.2
    pullPolicy: Always
  logstashHosts: [] # external logstash hosts with ports; override with actual data

prometheusExporter:
  enabled: false
  image:
    repository: mirantisworkloads/
    name: mongodb-prometheus-exporter
    tag: 1.0.0
    pullPolicy: Always
