# Default values for mongodb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: mirantisworkloads/
  name: mongodb
  tag: "3.4-r1"
  pullPolicy: Always
configServer:
  replicas: 3
  port: 27019
shard:
  replicas: 3
  port: 27019
resources:
  requests:
    cpu: 100m
    memory: 128Mi
