{{- if .Values.ui.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fission-ui" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fission-fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      name: {{ template "fission-ui" . }}
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ template "fission-fullname" . }}
        type: ui
    spec:
      containers:
      - name: fission-ui
        image: {{ .Values.ui.image.repository }}{{ .Values.ui.image.name }}:{{ .Values.ui.image.tag }}
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: conf
        configMap:
          name: {{ printf "fission-ui-fb-%s" .Release.Name | trunc 63 | trimSuffix "-" }}
{{- end -}}
