{{- if .Values.ui.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ printf "fission-ingress-%s" .Release.Name | trunc 55 | trimSuffix "-" }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fission-fullname" . }}
  annotations:
{{ toYaml .Values.ui.ingress.annotations | indent 4 }}
spec:
  {{- if .Values.ui.ingress.tls.enabled }}
  tls:
    - hosts:
      {{- range .Values.ui.ingress.hosts }}
      - {{ . }}
      {{- end }}
      secretName: {{ .Values.ui.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- range .Values.ui.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - backend:
              serviceName: {{ template "fission-ui" . }}
              servicePort: {{ $.Values.port }}
    {{- end -}}
{{- end -}}
