apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ printf "bfd-akka-ingest-%s" .Release.Name  | trunc 55 | trimSuffix "-" }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ printf "bfd-akka-ingest-%s" .Release.Name  | trunc 55 | trimSuffix "-" }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        heritage: "{{ .Release.Service }}"
        release: "{{ .Release.Name }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ printf "bfd-akka-ingest-%s" .Release.Name  | trunc 55 | trimSuffix "-" }}
    spec:
      containers:
      - name: akka-ingest
        image: {{ .Values.ingest.image.repository }}{{ .Values.ingest.image.name }}:{{ .Values.ingest.image.tag }}
        imagePullPolicy: {{ .Values.ingest.image.pullPolicy }}
        env:
        - name: CASSANDRA_CONNECT
          value: "{{ template "bfd.cassandra-host" . }}:{{ template "bfd.cassandra-port" . }}"
        - name: KAFKA_CONNECT
          value: "{{ template "bfd.kafka-address" . }}"
        resources:
{{ toYaml .Values.ingest.resources | indent 12 }}
