name: fission
description: |
  Fission is a fast serverless framework for Kubernetes with a focus on developer
  productivity and high performance.
version: 2.0.4
icon: https://mirantisworkloads.storage.googleapis.com/icons/fission.png
