image:
  repository: fission/
  name: fission-bundle
  tag: nightly20170705
  pullPolicy: IfNotPresent

controller:
  replicas: 1
  port: 80
  persistence:
    type: emptyDir # or hostPath or PersistentVolumeClaim
    #storageClass: ""
    volumeSize: 10Gi
    hostPath: ""
  service:
    type: NodePort # or ClusterIP or LoadBalancer
    nodePort: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    annotations: {}

router:
  replicas: 1
  port: 80
  service:
    type: NodePort # or ClusterIP or LoadBalancer
    nodePort: ""
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    annotations: {}

ui:
  enabled: false
  image:
    repository: fission/
    name: fission-ui
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    type: NodePort # or ClusterIP or LoadBalancer
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    annotations: {}
  ingress:
    enabled: false
    hosts: []
      #   - some.domain
    tls:
      enabled: false
      secretName: ""
    annotations: {}
      #   kubernetes.io/ingress.class: nginx

poolmgr:
  replicas: 1
  port: 80

kubewatcher:
  replicas: 1

logCollector:
  enabled: false
  replicas: 1
  image:
    repository: mirantisworkloads/
    name: filebeat
    tag: 5.2.2
    pullPolicy: IfNotPresent
  # external logstash hosts
  logstashHost:
    - "" # host:port

etcd:
  replicas: 1
  # if disabled, subchart will not be deployed
  deployChart: true
  # this address will be used if subchart deployment is disabled
  externalAddress: ""
