ports:
  default:
    port: 8088
  http:
    port: 8087
  defaultUdp:
    port: 8087
    protocol: udp

replicas: 1
probeInitialDelaySeconds: 15
probeTimeoutSeconds: 5

environment_variables:
  - name: INFLUXDB_ADMIN_ENABLED
    value: "true"

image:
  repository: ""
  name: "influxdb"
  tag: "1.3.4"
  pullPolicy: "IfNotPresent"

testImage:
  repository: "mirantisworkloads/"
  name: "test-base"
  tag: "1.0.0"
  pullPolicy: "IfNotPresent"

# Configure additional databases and listen interfaces for them
additionalDatabasesInterfacesConfigs:
  # sample graphite config
  graphite:
    # standard values
    enabled: false
    port: 2003
    #database: ""
    # additional values
    additionalValues: |
      log-enabled = true
      retention-policy = ""
      protocol = "tcp"
      batch-size = 5000
      batch-pending = 10
      batch-timeout = "1s"
      consistency-level = "one"
      separator = "."
      udp-read-buffer = 0

persistence:
  type: emptyDir
  #storageClass: ""
  #volumeSize: 1Gi
  #persistentVolumeType: "ReadWriteOnce"
  #hostPath: ""


# Configure resource requests and limits.
resources:
  #requests:
  #  memory: "256Mi"
  #  cpu: "250m"
  #limits:
    #cpu: "256Mi"
    #memory: "250m"

deployment:
  annotations: {}

service:
  type: "NodePort"
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  annotations: {}

#create initial database in influxdb
dbInit: # or dbInit: {} to leve empty influx
  dbName: default_init_db

