# Default values for kafka.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: 3
antiAffinity: "hard" # or "soft"
probeInitialDelaySeconds: 15
probeTimeoutSeconds: 5
port: 9092

image:
  repository: 127.0.0.1:31500/kafka
  tag: latest
  pullPolicy: Always

heapSize: 1G

persistence:
  enabled: false
  #storageClass: glusterfs
  volumeSize: "10Gi"
