# Default values for kafka.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: 3
antiAffinity: "hard" # or "soft"
probeInitialDelaySeconds: 15
probeTimeoutSeconds: 5
port: 9092

image:
  repository: mirantisworkloads/
  name: kafka
  tag: 0.10.2.0
  pullPolicy: Always

persistence:
  type: emptyDir # or hostPath or PersistentVolumeClaim

  #storageClass: ""
  volumeSize: 10Gi

  hostPath: ""

prometheusExporter:
  enabled: false

heapSize: 1G
resources:
  requests:
    cpu: 1
    memory: 1Gi
  #limits:
    #cpu: 4
    #memory: 4Gi

zookeeper:
  # if disabled, subchart will not be deployed
  deployChart: true
  # this address will be used if subchart deployment is disabled
  externalAddress: ""

logCollector:
  enabled: false
  image:
    repository: mirantisworkloads/
    name: filebeat
    tag: 5.2.2
    pullPolicy: Always
  # external logstash hosts
  logstashHost:
    - "" # host:port
  
