apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "curator-cm-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "curator-fullname" . }}
data:
  config.yml: |-
    ---
    client:
      hosts:
        - {{ template "elasticsearch-fqdn" . }}
      port: {{ int .Values.elasticsearch.port | default 9200 }}
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False

    logging:
      loglevel: INFO
      logfile:
      logformat: default
  {{- range $name, $content := .Values.configurations }}
  {{ $name }}: |
{{ $content | indent 4 }}
  {{- end }}
