apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: {{ template "curator-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "curator-fullname" . }}-job
spec:
  schedule: {{ .Values.schedule | quote  }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            heritage: "{{ .Release.Service }}"
            release: "{{ .Release.Name }}"
            chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
            app: {{ template "curator-fullname" . }}
        spec:
          containers:
          - name: "{{ template "curator-fullname" . }}-schedule"
            image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
            resources:
{{ toYaml .Values.resources | indent 14 }}
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: {{ template "curator-cm-fullname" . }}
          restartPolicy: OnFailure
