apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kib-cm-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "kib-fullname" . }}
data:
  kibana-conf: |
    server.port: {{ .Values.port }}
    server.host: 0.0.0.0
    server.name: "kibana"
    elasticsearch.url: "http://{{ template "kib-es-url" .  }}"
    elasticsearch.preserveHost: {{ .Values.elasticsearchConfig.preserveHost }}
    elasticsearch.requestTimeout:  {{ .Values.elasticsearchConfig.requestTimeout }}
    elasticsearch.shardTimeout: {{ .Values.elasticsearchConfig.shardTimeout }}
    elasticsearch.startupTimeout: {{ .Values.elasticsearchConfig.startupTimeout }}
    elasticsearch.tribe.ssl.verify: false
    kibana.index: ".kibana"
    kibana.defaultAppId: "dashboard/Main"
