apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "datanode-fullname" . }}
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: {{ template "datanode-fullname" . }}
spec:
  replicas: {{ .Values.dataNodeReplicas }}
  template:
    metadata:
      labels:
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        app: {{ template "datanode-fullname" . }}
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
        {
            "name": "wait-namenode",
            "image": "uhopper/hadoop-datanode:2.7.2",
            "imagePullPolicy": "IfNotPresent",
            "command": ["bash", "-c", "while [[ $ready != 0 ]]; do curl {{ template "namenode-address" . }}:50070; ready=$?; sleep 3; done"]
        }]'
    spec:
      containers:
        - name: datanode
          image: uhopper/hadoop-datanode:2.7.2
          env:
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://{{ template "namenode-address" . }}:8020
            - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              value: "false"
            - name: HDFS_CONF_dfs_client_use_datanode_hostname
              value: "false"
            - name: HDFS_CONF_dfs_datanode_use_datanode_hostname
              value: "false"
          livenessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /
              port: 50075
          volumeMounts:
            - name: hdfs-configs
              mountPath: /etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
          #  - name: hdfs-data
          #    mountPath: /hadoop/dfs/data
      volumes:
        - configMap:
            name: {{ template "configmap-fullname" . }}
            items:
            - key: hdfs-site.xml
              path: hdfs-site.xml
          name: hdfs-configs
      #  - name: hdfs-data
      #    hostPath:
      #      path: {{ .Values.dataNodeHostPath }}
