apiVersion: v1
kind: Service
metadata:
  name: {{ template "namenode-fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: {{ template "namenode-fullname" . }}
spec:
  ports:
  - port: 8020
    name: fs
  clusterIP: None
  selector:
    app: {{ template "namenode-fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ printf "hdfs-ui-%s" .Release.Name  | trunc 63 | trimSuffix "-" }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: "{{ printf "hdfs-ui-%s" .Release.Name  | trunc 63 | trimSuffix "-" }}"
spec:
  type: NodePort
  ports:
  - port: 50070
    name: ui
  selector:
    app: {{ template "namenode-fullname" . }}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "namenode-fullname" . }}
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: {{ template "namenode-fullname" . }}
spec:
  serviceName: {{ template "namenode-fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        app: {{ template "namenode-fullname" . }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: hdfs-namenode
          image: uhopper/hadoop-namenode:2.7.2
          env:
            - name: CLUSTER_NAME
              value: hdfs-k8s
            - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              value: "false"
            - name: HDFS_CONF_dfs_client_use_datanode_hostname
              value: "false"
            - name: HDFS_CONF_dfs_datanode_use_datanode_hostname
              value: "false"
          ports:
          - containerPort: 8020
            name: fs
          volumeMounts:
            - name: hdfs-configs
              mountPath: /etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
          #  - name: hdfs-name
          #    mountPath: /hadoop/dfs/name
      volumes:
        - configMap:
            name: {{ template "configmap-fullname" . }}
            items:
            - key: hdfs-site.xml
              path: hdfs-site.xml
          name: hdfs-configs
      #  - name: hdfs-name
      #    hostPath:
      #      path: {{ .Values.nameNodeHostPath }}
