ignored = [
  "k8s.io/client-go/pkg/api/v1",
  "k8s.io/client-go/pkg/apis/rbac/v1beta1"
]

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "~0.3.0"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "~1.3.1"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "~2.13.0"

[[constraint]]
  name = "github.com/Masterminds/vcs"
  version = "~1.11.0"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "^4.0.0"

[[constraint]]
  name = "github.com/evanphx/json-patch"

[[constraint]]
  name = "github.com/ghodss/yaml"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "^0.2.1"

[[constraint]]
  name = "github.com/gogo/protobuf"

[[constraint]]
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/gosuri/uitable"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/pflag"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "github.com/technosophos/moniker"

[[constraint]]
  name = "golang.org/x/crypto"

[[constraint]]
  name = "golang.org/x/net"

[[override]]
  name = "google.golang.org/grpc"
  version = "1.2.1"

[[constraint]]
   name = "k8s.io/api"
   branch = "release-1.8"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "~1.8.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v5.0.0"

[[constraint]]
  name = "k8s.io/helm"
  version = "v2.7.2"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.8"

[[override]]
  name = "k8s.io/apiserver"
  branch = "release-1.8"

[[override]]
  name = "k8s.io/metrics"
  branch = "release-1.8"

[[constraint]]
  name = "github.com/ugorji/go"
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"

[[constraint]]
  name = "github.com/aryann/difflib"

[[constraint]]
  name = "github.com/mgutz/ansi"

[[constraint]]
  name = "github.com/databus23/helm-diff"

[[override]]
  name = "github.com/docker/distribution"
  branch = "master"

