apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ printf "tweeviz-%s" .Release.Name  | trunc 63 | trimSuffix "-" }}"
  annotations:
    helm.sh/created: {{.Release.Time.Seconds | quote }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: "{{ printf "tweeviz-%s" .Release.Name  | trunc 63 | trimSuffix "-" }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ printf "tweeviz-%s" .Release.Name  | trunc 63 | trimSuffix "-" }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: TWEEVIZ_HDFS_ADDRESS
          value: "{{ .Values.hdfs.address }}"
        - name: TWEEVIZ_HDFS_PORT
          value: "{{ .Values.hdfs.port }}"
        - name: TWEEVIZ_HDFS_PATH
          value: "{{ .Values.hdfs.path }}"
        - name: TWEEVIZ_MIN_POPULARITY
          value: "{{ .Values.minPopularity }}"
        - name: TWEEVIZ_TOP_LIST_SIZE
          value: "{{ .Values.topListSize }}"
        resources:
{{ toYaml .Values.resources | indent 12 }}
