# Default values for tweeviz.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: mirantisworkloads/
  name: gerrit
  tag: "2.14.4"
  pullPolicy: IfNotPresent

port: 8080

service:
  type: NodePort # or ClusterIP or LoadBalancer

  nodePort: ""

  loadBalancerIP: ""
  loadBalancerSourceRanges: []

  annotations: {}

ingress:
  enabled: false
  hosts: []
    #- some.domain
  tls:
    enabled: false
    secretName: ""
  annotations: {}
    #kubernetes.io/ingress.class: nginx

resources:
  #requests:
  #  cpu: 100m
  #  memory: 512Mi
  #limits:
  #  cpu: 100m
  #  memory: 512Mi
