name: postgresql
version: 1.2.3
description: Object-relational database management system (ORDBMS) with an emphasis on extensibility and on standards-compliance.
appVersion: 9.6.2
icon: https://www.postgresql.org/media/img/about/press/elephant.png