apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "halyard.fullname" . }}-halconfig
  labels:
    app: {{ template "halyard.fullname" . }}
data:
  halconfig: |
{{ .Values.halconfig | indent 4 }}