apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "halyard.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "halyard.fullname" . }}