# Default values for tweeviz.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: frostman/
  name: tweeviz
  tag: latest
  pullPolicy: Always

port: 8589
minPopularity: 1
topListSize: 0

service:
  type: ClusterIP # or NodePort or LoadBalancer

  nodePort: ""

  loadBalancerIP: ""
  loadBalancerSourceRanges: []

  annotations: {}

ingress:
  enabled: false
  hosts: []
    #- some.domain
  tls:
    enabled: false
    secretName: ""
  annotations: {}
    #kubernetes.io/ingress.class: nginx

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  #limits:
  #  cpu: 100m
  #  memory: 512Mi

hdfs:
  # if disabled, subchart will not be deployed
  deployChart: true
  path: /

  # these values should be set if subchart deployment is disabled:
  externalAddress: ""
  externalPort: 8020
