apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "rollout.fullname" . }}-jenkins-trigger
  labels:
    app: {{ template "rollout.fullname" . }}-jenkins-trigger
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded
    "helm.sh/hook-weight": "2"
spec:
  template:
    metadata:
      labels:
        app: {{ template "rollout.fullname" . }}-jenkins-trigger
    spec:
      restartPolicy: OnFailure
      containers:
      - name: app
        image: "{{ .Values.spinnaker.jenkins.Agent.image.repository }}{{ .Values.spinnaker.jenkins.Agent.image.name }}:{{ .Values.spinnaker.jenkins.Agent.image.tag }}"
        command:
        - "sh"
        - "-cxe"
        - |
          JENKINS_POD=$(kubectl get pods -l app={{ template "jenkins.master-fullname" . }} | grep jenkins | awk '{print $1}')
          kubectl cp ~/.ssh/id_rsa $JENKINS_POD:/var/jenkins_home/
          kubectl cp /tmp/config/gerrit-trigger.xml $JENKINS_POD:/var/jenkins_home/
          kubectl exec $JENKINS_POD -- java -jar /var/jenkins_home/war/WEB-INF/jenkins-cli.jar -s http://:8080 restart
        volumeMounts:
        - mountPath: /tmp/config
          name: config
      volumes:
      - name: config
        configMap:
          name: {{ template "rollout.fullname" . }}-trigger