elasticsearch:
  # if disabled, subchart will not be deployed
  deployChart: true
  # this address will be used if subchart deployment is disabled
  externalAddress: ""

schedule: "@daily"

configurations:
  action_file.yml: |-
    ---
    actions:
      1:
        action: delete_indices
        description: >-
          Delete indices older than 30 days (based on index name), for logstash-
          prefixed indices. Ignore the error if the filter does not result in an
          actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          ignore_empty_list: True
          timeout_override:
          continue_if_exception: False
          disable_action: False
        filters:
          - filtertype: pattern
            kind: prefix
            value: logstash-
            exclude:
          - filtertype: age
            source: name
            direction: older
            timestring: '%Y.%m.%d'
            unit: days
            unit_count: 30
            exclude:

image:
  repository: "bobrik/"
  name: "curator"
  tag: "5.2.0"
  pullPolicy: "IfNotPresent"

# Configure resource requests and limits.
resources:
  #requests:
  #  memory: "256Mi"
  #  cpu: "250m"
  #limits:
    #cpu: "256Mi"
    #memory: "250m"

