apiVersion: servicecatalog.k8s.io/v1alpha1
kind: Instance
metadata:
  name: "zookeeper"
  namespace: "test-ns" # secret's namespace
spec:
  serviceClassName: "zookeeper1.0.0"
  planName: "default"
  parameters:
    name: "zookeeper"
    namespace: "test-ns" # instance's namespace
    version: "1.0.0"
    values:
      replicas: 1
      resources:
        requests:
          cpu: 0
          memory: 0Gi
