kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "fb-spark-%s" .Release.Name | trunc 63 | trimSuffix "-" }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
data:
  filebeat-yml: |-
    filebeat.prospectors:
      - input_type: log
        paths:
        - /var/log/spark/*.log
        fields:
          log_host: "spark"
    output.logstash:
      hosts:
      {{- range .Values.logCollector.logstashHost }}
      - {{ . | quote }}
      {{- end }}
    path:
      data: "/usr/share/filebeat/data"
      home: "/usr/share/filebeat"
