apiVersion: v1
kind: Service
metadata:
  name: {{ template "master-fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
spec:
  ports:
    - port: {{.Values.Master.ServicePort}}
      targetPort: {{.Values.Master.ContainerPort}}
  selector:
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "webui-fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
spec:
  type: {{ .Values.WebUi.serviceType }}
  ports:
    - port: {{.Values.WebUi.ServicePort}}
      targetPort: {{.Values.WebUi.ContainerPort}}
      {{- if .Values.WebUi.nodePort }}
      nodePort: {{.Values.WebUi.nodePort}}
      {{- end }}
  selector:
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
{{- if .Values.WebUi.externalIPs }}
  externalIPs:
{{ toYaml .Values.WebUi.externalIPs | indent 4 }}
{{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "restapi-fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
spec:
  ports:
    - port: {{.Values.Rest.ServicePort}}
      targetPort: {{.Values.Rest.ContainerPort}}
  selector:
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "master-fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
spec:
  replicas: {{default 1 .Values.Master.Replicas}}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{.Release.Name}}-{{.Values.Master.Component}}"
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: "{{.Release.Name}}-{{.Values.Master.Component}}"
      {{- if .Values.monitoring }}
      annotations:
        prometheus.io/scrape: "true"
      {{- end }}
    spec:
      containers:
        - name: {{ template "master-fullname" . }}
          image: "{{.Values.Master.Image}}:{{.Values.Master.ImageTag}}"
          imagePullPolicy: {{ .Values.Master.imagePullPolicy }}
          command:
            - /usr/local/spark/sbin/start-master.sh
          resources:
            requests:
              cpu: "{{.Values.Master.Cpu}}"
              memory: "{{.Values.Master.Memory}}"
          env:
          {{- if .Values.monitoring }}
          - name: SPARK_DAEMON_JAVA_OPTS
            value: "-javaagent:/usr/local/spark/jmx_prometheus_javaagent-0.9.jar=7072:/usr/local/spark/conf/spark-jmx.yml"
          {{- end }}
          - name: SPARK_DAEMON_MEMORY
            value: {{ default "1g" .Values.Master.DaemonMemory | quote }}
          - name: SPARK_NO_DAEMONIZE
            value: "1"
          {{- if .Values.monitoring }}
          ports:
          - name: jmx-agent
            containerPort: 7072
          {{- end }}
          volumeMounts:
            - name: spark-conf
              mountPath: /usr/local/spark/conf
      volumes:
        - name: spark-conf
          configMap:
            name: {{ printf "spark-conf-%s" .Release.Name | trunc 24 }}
