dashboard:
  service:
    externalIPs:
    - "${BFD_EXTERNAL_IP}"

spark:
  deployChart: false
  externalAddress: "spark-master-${BFD_SPARK_RELEASE}-0:7077"

cassandra:
  deployChart: false
  externalHost: "cassandra-${BFD_CASSANDRA_RELEASE}"
  externalPort: 9042

kafka:
  deployChart: false
  externalAddress: "kafka-${BFD_KAFKA_RELEASE}-0.kafka-${BFD_KAFKA_RELEASE}:9092"
