apiVersion: v1
kind: Service
metadata:
  name: {{ template "master-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "master-fullname" . }}
spec:
  ports:
    - name: rpc
      port: {{ .Values.spark.master.rpcPort }}
  clusterIP: None
  selector:
    app: {{ template "master-fullname" . }}
