image:
  repository: openzipkin/
  name: zipkin
  tag: 1
  pullPolicy: Always

port: 9411

# Environment settings can be found here: https://github.com/openzipkin/zipkin/tree/master/zipkin-server#environment-variables
# Note that the following variables will be overriden:
# - QUERY_PORT
env:
  SELF_TRACING_ENABLED: "true"

service:
  type: NodePort # or ClusterIP or LoadBalancer

  nodePort: ""

  loadBalancerIP: ""
  loadBalancerSourceRanges: []

  annotations: {}

ingress:
  enabled: false
  hosts: []
    #- some.domain
  tls:
    enabled: false
    secretName: ""
  annotations: {}
    #kubernetes.io/ingress.class: nginx

resources:
  #requests:
  #  cpu: 100m
  #  memory: 512Mi
  #limits:
  #  cpu: 100m
  #  memory: 512Mi

