image:
  repository: openzipkin/
  name: zipkin
  tag: 1
  pullPolicy: Always

port: 9411

probeInitialDelaySeconds: 15
probeTimeoutSeconds: 5

prometheusExporter:
  enabled: false

# Environment settings can be found here: https://github.com/openzipkin/zipkin/tree/master/zipkin-server#environment-variables
# Note that the following variables will be overriden:
# - QUERY_PORT
# if cassandra.deployChart is enabled, the following variables will be
# also overriden:
# - STORAGE_TYPE=cassandra
# - CASSANDRA_CONTACT_POINTS
# if elasticsearch.deployChart is enabled, the following variables will be
# also overriden:
# - STORAGE_TYPE=elasticsearch
# - ES_HOSTS
env:
  SELF_TRACING_ENABLED: "true"

dependenciesJob:
  # The zipkin dependencies job pre-aggregates data to show links between
  # services. Currently not working for cassandra3 storage type.
  enabled: false
  schedule: "@daily"
  image:
    repository: openzipkin/
    name: zipkin-dependencies
    tag: 1
    pullPolicy: Always

service:
  type: NodePort # or ClusterIP or LoadBalancer

  nodePort: ""

  loadBalancerIP: ""
  loadBalancerSourceRanges: []

  annotations: {}

ingress:
  enabled: false
  hosts: []
    #- some.domain
  tls:
    enabled: false
    secretName: ""
  annotations: {}
    #kubernetes.io/ingress.class: nginx

resources:
  #requests:
  #  cpu: 100m
  #  memory: 512Mi
  #limits:
  #  cpu: 100m
  #  memory: 512Mi

cassandra:
  # Use cassandra as a storage
  # if disabled, subchart will not be deployed. To configure access to external
  # cassandra, provide corresponding environment variables in `env` section:
  # https://github.com/openzipkin/zipkin/tree/master/zipkin-server#cassandra-storage
  deployChart: false

elasticsearch:
  # Use elasticsearch as a storage
  # if disabled, subchart will not be deployed. To configure access to external
  # elasticsearch, provide corresponding environment variables in `env` section:
  # https://github.com/openzipkin/zipkin/tree/master/zipkin-server#elasticsearch-storage
  deployChart: false
