apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "broker-cfg" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-broker"
data:
  broker-config.json: >
    {
      "chartUrls": {{ .Values.config.chartUrls | toJson }},
      "tillerHost": {{ .Values.config.tillerHost | quote }}
    }
