{{- if .Values.monitoring }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "cm-cas-%s" .Release.Name | trunc 24 }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ printf "cas-%s" .Release.Name  | trunc 24 }}
data:
  cassandra-jmx.yml: |-
    ---
    lowercaseOutputLabelNames: true
    lowercaseOutputName: true
    rules:
    - pattern: org.apache.cassandra.metrics<type=(Connection|Streaming), scope=(\S*), name=(\S*)><>(Count|Value)
      name: cassandra_$1_$3
      labels:
        address: "$2"
    - pattern: org.apache.cassandra.metrics<type=(\S*)(?:, ((?!scope)\S*)=(\S*))?(?:, scope=(\S*))?,
        name=(\S*)><>(Count|Value)
      name: cassandra_$1_$5
      labels:
        "$1": "$4"
        "$2": "$3"
{{- end }}
