kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "cas-fb-%s" .Release.Name | trunc 63 | trimSuffix "-" }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ printf "cas-%s" .Release.Name  | trunc 63 | trimSuffix "-" }}
data:
  filebeat-yml: |-
    filebeat.prospectors:
      - input_type: log
        paths:
        - "/var/log/cassandra/*.log"
        fields:
          log_host: "cassandra"
        multiline:
          pattern: '^[[:space:]]+|^Caused by:'
          negate: false
          match: after
    output.logstash:
      hosts:
      {{- range .Values.logCollector.logstashHost }}
      - {{ . | quote }}
      {{- end }}
    path:
      data: "/usr/share/filebeat/data"
      home: "/usr/share/filebeat"
