apiVersion: v1
kind: Service
metadata:
  name: {{ template "fission-router" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fission-fullname" . }}
    type: router
  {{- if .Values.router.service.annotations }}
  annotations:
{{ toYaml .Values.router.service.annotations | indent 4}}
  {{- end }}
spec:
  type: {{ .Values.router.service.type | quote }}
  ports:
  - port: {{ .Values.router.port }}
    {{- if eq .Values.router.service.type "NodePort" }}
    {{- if .Values.router.service.nodePort }}
    nodePort: {{ .Values.router.service.nodePort }}
    {{- end -}}
    {{- end }}
  selector:
    app: {{ template "fission-fullname" . }}
    type: router
  {{- if eq .Values.router.service.type "LoadBalancer" }}
  {{- if .Values.router.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.router.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.router.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.router.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
  {{- end -}}
