apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: TWEEPUB_APP_KEY
          value: "{{ .Values.twitter.appKey }}"
        - name: TWEEPUB_APP_SECRET
          value: "{{ .Values.twitter.appSecret }}"
        - name: TWEEPUB_TOKEN_KEY
          value: "{{ .Values.twitter.tokenKey }}"
        - name: TWEEPUB_TOKEN_SECRET
          value: "{{ .Values.twitter.tokenSecret }}"
        - name: TWEEPUB_FOLLOW
          value: "{{ .Values.twitter.follow }}"
        - name: TWEEPUB_TRACK
          value: "{{ .Values.twitter.track }}"
        - name: TWEEPUB_LOCATIONS
          value: "{{ .Values.twitter.locations }}"
        - name: TWEEPUB_LANGUAGES
          value: "{{ .Values.twitter.languages }}"
        - name: TWEEPUB_KAFKA
          value: {{ template "kafka-address" . }}
        - name: TWEEPUB_TOPIC
          value: "{{ .Values.kafka.topic }}"
        resources:
{{ toYaml .Values.resources | indent 12 }}
