replicas: 3
antiAffinity: "hard" # or "soft" or "null"
probeInitialDelaySeconds: 15
probeTimeoutSeconds: 5

image:
  repository: mirantisworkloads/redis
  tag: 3.2
  pullPolicy: Always

resources:
  requests:
    memory: 256Mi
    cpu: 100m

## Persist data to a persitent volume
persistence:
  type: emptyDir # or hostPath or PersistentVolumeClaim
  hostPath: ""
  ## storageClass: generic
  volumeSize: 5Gi

## Change redis configuration paramaters below.
config:
  redisPort: 6379
  sentinelPort: 26379
  slaveReadOnly: "no"
