replicas: 3
antiAffinity: "soft" # or "hard"

peerPort: 2380
clientPort: 2379

image:
  repository: mirantisworkloads/
  name: etcd-amd64
  tag: 3.0.17
  pullPolicy: IfNotPresent

persistence:
  type: emptyDir # or hostPath or PersistentVolumeClaim

  #storageClass: ""
  volumeSize: 10Gi

  hostPath: ""

resources:
  #requests:
  #  cpu: 100m
  #  memory: 512Mi
  #limits:
  #  cpu: 4
  #  memory: 10Gi
