apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "es-client-cm-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "es-client-fullname" . }}
data:
  elasticsearch.yml: |
    node.data: ${NODE_DATA}
    node.master: ${NODE_MASTER}
    node.name: ${HOSTNAME}

    processors: {{ .Values.client.config.processors }}

    network.host: 0.0.0.0

    cloud:
      kubernetes:
        service: ${SERVICE}
        namespace: ${KUBERNETES_NAMESPACE}

    discovery.zen.minimum_master_nodes: ${MINIMUM_MASTER_NODES:2}
    discovery.zen.hosts_provider: kubernetes
    discovery.zen.master_election.ignore_non_master_pings: true

    thread_pool.search.size: {{ .Values.client.config.thread_pool.search.size }}
    thread_pool.search.queue_size: {{ .Values.client.config.thread_pool.search.queue_size }}
    thread_pool.bulk.size: {{ .Values.client.config.thread_pool.bulk.size }}
    thread_pool.bulk.queue_size: {{ .Values.client.config.thread_pool.bulk.queue_size }}
    thread_pool.index.size: {{ .Values.client.config.thread_pool.index.size }}
    thread_pool.index.queue_size: {{ .Values.client.config.thread_pool.index.queue_size }}
