apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "es-client-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "es-fullname" . }}
    type: client
spec:
  replicas: {{ .Values.client.replicas }}
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ template "es-fullname" . }}
        type: client
    spec:
      containers:
      - name: elasticsearch
        env:
        - name: SERVICE
          value: {{ template "es-fullname" . }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_DATA
          value: "false"
        - name: NODE_MASTER
          value: "false"
        - name: MINIMUM_MASTER_NODES
          value: {{ .Values.master.quorum | quote }}
        - name: ES_JAVA_OPTS
          value: "-Xms{{ .Values.client.heapSize }} -Xmx{{ .Values.client.heapSize }}"
        image: "{{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        securityContext:
          privileged: true
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        command:
        - elasticsearch
        resources:
{{ toYaml .Values.client.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.port }}
          name: http
        - containerPort: {{ .Values.transportPort }}
          name: transport
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.port }}
          timeoutSeconds: {{ .Values.probeTimeoutSeconds }}
          initialDelaySeconds: {{ .Values.probeInitialDelaySeconds }}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          name: config
          subPath: elasticsearch.yml
        - mountPath: /usr/share/elasticsearch/config/log4j2.properties
          name: shared-config
          subPath: log4j2.properties
      volumes:
      - name: config
        configMap:
          name: {{ template "es-master-cm-fullname" . }}
      - name: shared-config
        configMap:
          name: {{ template "es-cm-fullname" . }}
