{{- if .Values.client.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ printf "elasticsearch-ingress-%s" .Release.Name | trunc 55 | trimSuffix "-" }}
  annotations:
  {{- range $key, $value := .Values.client.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "es-fullname" . }}
spec:
  {{- if .Values.client.ingress.tls.enabled }}
  tls:
    - hosts:
      {{- range .Values.client.ingress.hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .Values.client.ingress.tls.secretName }}
  {{- end }}
  rules:
  {{- $ctx := . }}
  {{- range .Values.client.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "es-fullname" $ctx }}
              servicePort: {{ $.Values.port }}
  {{- end -}}
{{- end -}}
