apiVersion: v1
kind: Service
metadata:
  name: {{ template "vernemq.fullname" . }}
  labels:
    app: {{ template "vernemq.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  - name: websocket
    port: 8083
    targetPort: 8080
  selector:
    app: {{ template "vernemq.fullname" . }}

