apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.transportPort }}
      targetPort: {{ .Values.transportPort }}
  selector:
    app: {{ template "fullname" . }}
