apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "master-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
    type: master
spec:
  replicas: {{ .Values.master.replicas }}
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ template "fullname" . }}
        type: master
    spec:
      containers:
      - name: elasticsearch
        env:
        - name: SERVICE
          value: {{ template "fullname" . }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_DATA
          value: "false"
        - name: ES_JAVA_OPTS
          value: "-Xms{{ .Values.data.heapSize }} -Xmx{{ .Values.data.heapSize }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
        - elasticsearch
        resources:
{{ toYaml .Values.master.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.transportPort }}
          name: transport
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.port }}
          timeoutSeconds: {{ .Values.probeTimeoutSeconds }}
          initialDelaySeconds: {{ .Values.probeInitialDelaySeconds }}