twitter:
  appKey: APPKEY
  appSecret: APPSECRET
  tokenKey: TOKENKEY
  tokenSecret: TOKENSECRET

  locations: -71.4415,41.9860,-70.4747,42.9041

kafka:
  deployChart: false
  externalAddress: kafka-KAFKARl-0.kafka-KAFKARL:9092,kafka-KAFKARL-1.kafka-KAFKARL:9092,kafka-KAFKARL-2.kafka-KAFKARL:9092
  topic: twitter-stream
