kind: Service
apiVersion: v1
metadata:
  name: {{ template "redis-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "redis-fullname" . }}
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.config.redisPort }}
    name: redis
  selector:
    app: {{ template "redis-fullname" . }}
