kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "redis-fullname" . }} 
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "redis-fullname" . }}
data:
  redis.conf: |-
{{ .Values.config.redisParameters | indent 4 }}
    {{- if .Values.config.clusterEnabled }}
    cluster-enabled yes
    cluster-require-full-coverage no
    cluster-node-timeout 1000
    cluster-migration-barrier 1
    cluster-config-file nodes.conf
    {{- else }}
    cluster-enabled no
    {{- end }}
    appendonly yes
    protected-mode no
    daemonize no
    port {{ .Values.config.redisPort }}
    bind 0.0.0.0
    logfile "/var/log/redis/redis.log"
