apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
data:
{{ toYaml .Values.serverConfigFile | indent 2 }}
