apiVersion: v1
kind: Secret
metadata:
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "grafana.fullname" . }}
  name: {{ template "grafana.fullname" . }}
type: Opaque
data:
  {{- if .Values.adminPassword }}
  grafana-admin-password: {{ .Values.adminPassword | b64enc | quote }}
  {{- else }}
  grafana-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  grafana-admin-user: {{ .Values.adminUser | b64enc | quote }}
