apiVersion: v1
kind: Service
metadata:
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "fullname" . }}
  name: {{ template "fullname" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.port }}
      protocol: TCP
      targetPort: {{ .Values.port }}
  selector:
    app: {{ template "fullname" . }}
  type: "{{ .Values.service.type }}"
{{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end -}}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
{{- end -}}
{{- if eq .Values.service.type "NodePort" }}
  {{- if .Values.service.nodePort }}
  nodePort: {{ .Values.service.nodePort }}
  {{- end -}}
{{- end -}}
