# Default values for zookeeper.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: 3
antiAffinity: hard # or soft
probeInitialDelaySeconds: 15
probeTimeoutSeconds: 5
minAvailable: 2

serverPort: 2888
leaderElectionPort: 3888
clientPort: 2181

image:
  repository: 127.0.0.1:31500/zookeeper
  tag: latest
  pullPolicy: Always

persistence:
  enabled: false
  #storageClass: glusterfs
  volumeSize: 10Gi

heapSize: 1G
logLevel: INFO

# Zokeeper config (zoo.cfg) parameters
tickTime: 2000
initLimit: 10
syncLimit: 5
maxClientCnxns: 60
autopurge:
  purgeInterval: 1
  snapRetainCount: 3
monitoring: true
