spark:
  master:
    replicas: 1
  worker:
    replicas: 1

prometheusExporter:
  enabled: true

zookeeper:
  deployChart: false
  externalAddress: zk-${TS_ZOOKEEPER_RELEASE}-0.zk-${TS_ZOOKEEPER_RELEASE}:2181
