minPopularity: 1
topListSize: 25

storage: ${TS_STORAGE}

hdfs:
  deployChart: false
  path: /
  addresses:
    namenode: hdfs-namenode-${TS_HDFS_RELEASE}-0.hdfs-namenode-${TS_HDFS_RELEASE}:8020

cassandra:
  deployChart: false
  addresses:
    cassandra: cassandra-${TS_CASSANDRA_RELEASE}:9042
  keyspace: mirantis
  table: tweetics
