minHashtagCounts: 0

zookeeper:
  deployChart: false
  externalAddress: zk-${TS_ZOOKEEPER_RELEASE}-0.zk-${TS_ZOOKEEPER_RELEASE}:2181

kafka:
  deployChart: false
  externalAddress: kafka-${TS_KAFKA_RELEASE}-0.kafka-${TS_KAFKA_RELEASE}:9092
  topic: twitter-stream

spark:
  deployChart: false
  externalAddress: spark-master-${TS_SPARK_RELEASE}-0:7077

storage: ${TS_STORAGE}

hdfs:
  deployChart: false
  addresses:
    namenode: hdfs-namenode-${TS_HDFS_RELEASE}-0.hdfs-namenode-${TS_HDFS_RELEASE}:8020
  path: /twitter

cassandra:
  deployChart: false
  addresses:
    cassandra: cassandra-${TS_CASSANDRA_RELEASE}:9042
  keyspace: mirantis
  table: tweetics
