twitter:
  appKey: ${TS_APP_KEY}
  appSecret: ${TS_APP_SECRET}
  tokenKey: ${TS_TOKEN_KEY}
  tokenSecret: ${TS_TOKEN_SECRET}

  # San Francisco, Boston, New York
  locations: -71.4415,41.9860,-70.4747,42.9041,-122.75,36.8,-121.75,37.8,-74,40,-73,41

kafka:
  deployChart: false
  externalAddress: kafka-${TS_KAFKA_RELEASE}-0.kafka-${TS_KAFKA_RELEASE}:9092
  topic: twitter-stream
