apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mariadb-fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app: {{ template "mariadb-fullname" . }}
data:
  my.cnf: |-
{{- if .Values.config }}
{{ .Values.config | indent 4 }}
{{- end }}