apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mariadb-fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app: {{ template "mariadb-fullname" . }}
data:
  my.cnf: |-
    [mysqld]
    general-log = 1
    general-log-file = /opt/bitnami/mariadb/logs/mysqld.log
    log-error = /opt/bitnami/mariadb/logs/mysqld-error.log
    slow-query-log = 1
    long-query-time = 1
    slow-query-log-file = /opt/bitnami/mariadb/logs/mysqld-slow_query.log
    log-queries-not-using-indexes = 1
  filebeat-yml: |-
    filebeat.prospectors:
      - input_type: log
        paths:
        - /opt/bitnami/mariadb/logs/mysqld*.log
        fields:
          log_host: "mariadb"
    output.logstash:
      hosts:
      {{- range .Values.logCollector.logstashHost }}
      - {{ . | quote }}
      {{- end }}
    path:
      data: "/usr/share/filebeat/data"
      home: "/usr/share/filebeat"