apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "monocular.fullname" . }}-api-config
  labels:
    app: {{ template "monocular.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  monocular.yaml: |-
{{ toYaml .Values.api.config | indent 4 -}}
    mongodb:
      host: {{ template "monocular.mongodb-address" . }}
      database: {{ .Values.mongodb.database }}

    redis:
      host: {{ template "monocular.redis-address" . }}

    tillerPortForward: false