apiVersion: v1
kind: Service
metadata:
  name: {{ template "monocular.fullname" . }}-api
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.externalPort }}
    targetPort: {{ .Values.api.service.internalPort }}
    {{- if .Values.api.service.nodePort }}
    nodePort: {{ .Values.api.service.nodePort }}
    {{- end }}
    protocol: TCP
    name: {{ .Values.api.service.name }}
  selector:
    app: {{ template "monocular.fullname" . }}-api
