apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "monocular.fullname" . }}-ui-config
  labels:
    app: {{ template "monocular.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  overrides.js: |-
    window.monocular = {
      overrides: {
        googleAnalyticsId: '{{.Values.ui.googleAnalyticsId}}',
        appName: '{{.Values.ui.appName}}',
        {{- if .Values.ui.backendHostname }}
        backendHostname: '{{ .Values.ui.backendHostname }}',
        {{- end }}
        releasesEnabled: {{.Values.api.config.releasesEnabled}}
      }
    };
